# Shell script to run R scripts for 'panel 2'

# cytokine expressing memory T cells

Rscript analysis_CellCnn_PD1_panel2_CD4_Tmem_cells_base_combined.R
Rscript analysis_CellCnn_PD1_panel2_CD8_Tmem_cells_base_combined.R

Rscript analysis_CellCnn_PD1_panel2_CD4_Tmem_cells_treated_combined.R
Rscript analysis_CellCnn_PD1_panel2_CD8_Tmem_cells_treated_combined.R
